---
# yamllint disable rule:colons
#        _     _                         _          _       __         _      _
#   __  | |_  | |  ___  __ __ __  __ _  | |_   __  | |_    / _|  ___  | |  __| |  ___   _ _
#  / _| |  _| | | |___| \ V  V / / _` | |  _| / _| | ' \  |  _| / _ \ | | / _` | / -_) | '_|
#  \__|  \__| |_|        \_/\_/  \__,_|  \__| \__| |_||_| |_|   \___/ |_| \__,_| \___| |_|

# #############################################################################
#        _                 _
#   __  | |_    ___   __  | |__
#  / _| | ' \  / -_) / _| | / /
#  \__| |_||_| \___| \__| |_\_\
# #############################################################################
#check:

# #############################################################################
#               _                       _
#   ___  _ _   (_)  _ __   _ __   ___  | |_   ___
#  (_-< | ' \  | | | '_ \ | '_ \ / -_) |  _| (_-<
#  /__/ |_||_| |_| | .__/ | .__/ \___|  \__| /__/
#                  |_|    |_|
# #############################################################################

snippets:
  git:
    vcode: cat cli/releases.yaml|grep version|head -1|grep -oE '[0-9]+\.[0-9]+\.[0-9]'
    